### PR TITLE
Added a treeview for improved overview

### PR DESCRIPTION
**Pull request by Matt-17**
Hi, 

as sometimes I needed a better overview I added a TreeView to this extension. Maybe you're interested in this. 

If so, I can also improve my pull request, by now it's a bit quick&dirty.

### CODE REVIEW

**Comment by madskristensen** [comment]
Super cool. Do you have a screenshot?

**Comment by Matt-17** [comment]
Sure. Here is the screenshot: 
grafik

Also, here is a short video (gif): 


Let me know, if you have any improvement ideas.

**Comment by madskristensen** [comment]
I love it. It looks fantastic

**Comment by madskristensen** [comment]
Thank you so much!

**Pull request merged**
